### ISSUE TITLE
Change travel speed

### ISSUE THREAD

**Issue by blasco** [c-frame/aframe-cursor-teleport#16]
First of all, this component is amazing. Thank you very much for sharing it. I'm trying to modify the travel velocity, would it be interesting to add expose this parameter?

**Comment by mwbeene** [comment]
@blasco Thanks for trying it out and I like your suggestion. I'll see what I can do about exposing this.

**Comment by blasco** [comment]
That would be great! Looking forward to it. Also, this is related issue, is actually why I asked for being able to manipulate the speed. In low end devices the travel speed is very low (I thought it was the normal speed, but then I tried with a decent device and the speed was fine). So the player travel speed seems to depend on the tick update, giving different speeds depending on the device. I Unity the solution is to multiply increments in space by the deltaTime, I'm not sure if aframe there is something equivalent, so the speed is independent of the tick cycle and depends only on the ellapsed time. Do you know what I mean?

**Comment by vincentfretin** [comment]
You can calculate the transition position with the delta time yes, see #37

**Comment by vincentfretin** [comment]
@mwbeene You can close this issue now #37 is merged.
