### ISSUE TITLE
needs npm version bump to 0.0.6

### ISSUE THREAD

**Issue by kfarr** [c-frame/aframe-cursor-teleport#29]
~package.json says version 0.0.6, but~ latest on npm is 0.0.5 but that doesn't seem to include the new changes for a-frame 1.2+, can you bump to 0.0.6 and publish on npm?
https://www.npmjs.com/package/aframe-cursor-teleport-component

**Comment by vincentfretin** [comment]
I'll update the webpack stack and create a new release on npm soon.

**Comment by vincentfretin** [comment]
The examples needs to be updated to aframe 1.4.1 and using https://github.com/jure/aframe-blink-controls instead of teleport-controls.

**Comment by kfarr** [comment]
FYI when trying blink controls and the updated version of this cursor teleport component at the same time, blink controls didn't "just work" in VR out of the box. The next thing to try is removing cursor teleport / add blink controls when entering VR mode (and vice versa exiting)

**Comment by kfarr** [comment]
@vincentfretin updated a-frame and added blink controls here: https://github.com/c-frame/aframe-cursor-teleport/pull/50

**Comment by vincentfretin** [comment]
Version 1.1.1 is released.
