### ISSUE TITLE
Not working in Android Chrome

### ISSUE THREAD

**Issue by quantumalchemy** [c-frame/aframe-cursor-teleport#4]
* works in  android firefox
again Great addon for a-frame!

**Comment by mwbeene** [comment]
Just looking at this. I've been testing on my own Google Pixel and haven't encountered any issues. Can you describe what's happening or send me an example?

**Comment by oneWaveAdrian** [comment]
I experience the same issues in my app as well as your `basic demo` @mwbeene.
Android 9
Chrome 90.0.4430.210

Description:
Clicks on ground floor seem not to be registered and thus do not move the camera.
Clicks on objects work fine.

I can also confirm Firefox works perfectly on the same platform.

**Comment by vincentfretin** [comment]
I just tested https://c-frame.github.io/aframe-cursor-teleport/examples/basic/index.html on Chrome Android, I have no issue.
